# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  litellm = {
    pname = "litellm";
    version = "1.0.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/l/litellm/litellm-1.0.0.tar.gz";
      sha256 = "sha256-9nw97AzFYI7UkzwCB01BXO8CySyaDIjM2AP+kXKKVLE=";
    };
  };
  localai-x86_64-darwin-avx512 = {
    pname = "localai-x86_64-darwin-avx512";
    version = "1.40.0";
    src = fetchurl {
      url = "https://github.com/mudler/LocalAI/releases/download/v1.40.0/local-ai-avx512-Darwin-x86_64";
      sha256 = "sha256-MRoiKFwAZEoKOf+nOMVl+75+ceSKrm1VnuwWK9n1/eY=";
    };
  };
  localai-x86_64-linux-avx512 = {
    pname = "localai-x86_64-linux-avx512";
    version = "1.40.0";
    src = fetchurl {
      url = "https://github.com/mudler/LocalAI/releases/download/v1.40.0/local-ai-avx512-Linux-x86_64";
      sha256 = "sha256-ITdEn96zy3P9GPikOujGb4/AzsESWVOn5c9vrh+LEgY=";
    };
  };
  ollama-aarch64-darwin = {
    pname = "ollama-aarch64-darwin";
    version = "0.1.9";
    src = fetchurl {
      url = "https://github.com/jmorganca/ollama/releases/download/v0.1.9/ollama-darwin";
      sha256 = "sha256-htTv84CJ++xZxQc1NGd5x2D637xdaZStSRVi323Exxg=";
    };
  };
  ollama-aarch64-linux = {
    pname = "ollama-aarch64-linux";
    version = "0.1.9";
    src = fetchurl {
      url = "https://github.com/jmorganca/ollama/releases/download/v0.1.9/ollama-linux-arm64";
      sha256 = "sha256-J6NJ+UrVdcU/sg/YxOA53vkxLVgQ36nVm+sMMBzZxQc=";
    };
  };
  ollama-x86_64-darwin = {
    pname = "ollama-x86_64-darwin";
    version = "0.1.9";
    src = fetchurl {
      url = "https://github.com/jmorganca/ollama/releases/download/v0.1.9/ollama-darwin";
      sha256 = "sha256-htTv84CJ++xZxQc1NGd5x2D637xdaZStSRVi323Exxg=";
    };
  };
  ollama-x86_64-linux = {
    pname = "ollama-x86_64-linux";
    version = "0.1.9";
    src = fetchurl {
      url = "https://github.com/jmorganca/ollama/releases/download/v0.1.9/ollama-linux-amd64";
      sha256 = "sha256-ghEkGZN4uhKkHUCXTiTzllerbg+kNdWQznaX7aPsLAU=";
    };
  };
}
